### ISSUE TITLE
Indent guides indistinguisables from the background

### ISSUE THREAD

**Issue by Widcket** [tinacious/vscode-tinacious-design-syntax#1]
On vscode 1.7.1 indent guides are rendered like this:

![screen shot 2016-11-14 at 4 22 29 pm](https://cloud.githubusercontent.com/assets/5055789/20279287/c0e57052-aa86-11e6-81e1-ac5523dc611d.png)

Should be rendered like this:
![](https://raw.githubusercontent.com/tinacious/vscode-tinacious-design-syntax/master/images/01_javascript-angular.png)

Also the line numbers' colors may not match.

**Comment by tinacious** [comment]
Some changes have been added to make the highlighted line and comments a bit more visible.

The current version 0.2.4 looks like the following:

### Highlighted line

![image](https://cloud.githubusercontent.com/assets/1856992/23690621/1120e0c0-0391-11e7-8952-b1c939b7985d.png)

### Selected text

![image](https://cloud.githubusercontent.com/assets/1856992/23690663/79f668ae-0391-11e7-9080-14bb946e8f2b.png)

In order to see the whitespace indicators, you must first enable this setting by adding the following to your user `settings.json` config file:

```json
"editor.renderWhitespace": true
```

**Comment by tinacious** [comment]
With indent guides on in 0.2.4:

![image](https://cloud.githubusercontent.com/assets/1856992/23690752/0b3a6a7c-0392-11e7-929e-c96c0a103582.png)

**Comment by pzelnip** [comment]
This still doesn't quite seem right, even with the suggested settings I only see whitespace rendered when a line is selected.  Ideally I'd like the whitespace markers to be rendered *all* the time.

As well, guidelines don't seem to be rendered at all.  Compare (this is the dark+ theme):

![screen shot 2018-01-05 at 8 27 41 am](https://user-images.githubusercontent.com/414933/34618057-6c1aa0b0-f1f2-11e7-95e9-c4ea0aca45e6.png)

vs:

![screen shot 2018-01-05 at 8 28 07 am](https://user-images.githubusercontent.com/414933/34618073-75e8c0d6-f1f2-11e7-90ba-8444eaccc868.png)

This is with:

```
  "editor.renderWhitespace": "boundary",
  ""editor.renderIndentGuides": true,
```
in my user settings.
