### ISSUE TITLE
Comments are unreadable in diff view

### ISSUE THREAD

**Issue by wopian** [tinacious/vscode-tinacious-design-syntax#2]
Version: 0.2.2

The following piece of code:
```pug
              ) Characters

          //- start: favourites container
          .tab-content
            //- Display anime favourites when active
```

Is completely unreadable in VS Code's diff viewer. Not that they're that easy to read anyway.

![](http://i.imgur.com/itIZ7FG.png)

**Comment by tinacious** [comment]
Thanks for reporting!

**Comment by tinacious** [comment]
The inability to change git diff colours appears to be an open feature request with VSCode in their issue queue. https://github.com/Microsoft/vscode/issues/19735

**Comment by tinacious** [comment]
Microsoft has added the ability to theme diff colours using the user settings. Unfortunately this is not something provided by the tmTheme file modifications, so you would need to add it yourself.

You can add the following to your user settings:

```json
"workbench.colorCustomizations": {
  "diffEditor.insertedTextBackground": "#00D3641A",
  "diffEditor.removedTextBackground": "#FF339933"
}
```

![image](https://cloud.githubusercontent.com/assets/1856992/25773217/e5706fdc-3247-11e7-81a6-5e2f45d49e4a.png)

Since support was added to VSCode for this, I'm closing this issue.
